{
    "Header": {
        "ConversationID": "9edd8877-be06-482d-abc9-44c187d3c5e9",
        "CreationTime": "2023-09-22T16:42:49.351567+10:00",
        "MessageType": "ERX002",
        "Receiver": {
            "ErxAdapterURI": null,
            "ErxUserId": null,
            "OrganisationID": "HTWKV",
            "OrganisationUserId": null
        },
        "Sender": {
            "ErxAdapterURI": null,
            "ErxUserId": null,
            "OrganisationID": "00000",
            "OrganisationUserId": null
        },
        "Status": {
            "Code": null,
            "Description": null,
            "Details": null
        },
        "UUID": "280006cd-1416-4b07-8964-6063bb19e10a"
    },
    "payload": {
        "SCID": "2HTWKV0BRTXRBMJVX8",
        "GUID": "b491fd97-e7b9-45eb-8bdc-3046a3c95c4e",
        "CreatedDate": "2022-03-30T00:00:00",
        "OriginalSCID": null,
        "OriginalGUID": null,
        "NotificationConsentFlag": "true",
        "Status": null,
        "PrescriberToNotify": "HTWKV",
        "Items": {
            "Item": {
                "Sequence": "1",
                "OriginalSequence": null,
                "State": "Active",
                "SessionKey": {
                    "Key": "eKRUHgMttzk0pJFbkQb8nsBs/Rrsbk61LgwfPUzjHuHom6apuxOL6dbtV6WV4XThIDobH055CTaod3a7YBhz+4+fvtPngTrURyr5aQlAD/v4Tg7CpQV5bdl/5H4Bp1PhTdcuFmjHpT27YDoLzKfPQpYIWpyaTKwxH9IcgnG8kpW/rD82Y22xFBtXKnfg2FKQrPgP+fz5ymvSruHW6Cl8LmLm6+fEMfPvRzoCAK7d9nnilnXnFGgd6M4/yTmzu4hxqPp0CXl5JUmY8J6LvfT5nAM6Y/dPw7FpfA07BC3ccQbs5c3tbCK9ilwLeeaHWB+n5LOepZJXaathZjN7/EWZCg==",
                    "IV": "LqUqiDyMiLpwY2FAh+hWK+HEbLN8I1wwBkKrP0u6R9iF+Pi4AOYb/lJojLjkgDdyvLGxljcXXw3q2zcRPp6gBLVi/okO588roPva+GjqLuYvn5obIbfDzeIm2JWElttkk8S/lvPn+C2eQ8IWOCoNjCipXcE6eXWmc68/6SE870NjtMcB+OH2DevJJlq4BGEsofm3TdGTtlx4zE8r8zUZXTLqasufcPSctW8AfukkecYiKs3SR8QsiqaCBKiaDTmgoXjeiNRAeVoBjPohAbInHQewJhAjiJraNKWOVT0Sfyfbdwpk3c2dRSCTQjq9CxsCW1+tbueq7hsbNT4AtqY/Aw==",
                    "CertificateVersion": "v4"
                },
                "Content": {
                    "Patient": {
                        "PatientUniqueID": "1164",
                        "PatientNumber": "1164",
                        "PatientFamilyName": "DUNCAN",
                        "PatientFirstName": "CHRISTINE",
                        "PatientMedicareFamilyName": null,
                        "PatientMedicareFirstName": null,
                        "PatientTitle": "MISS",
                        "PatientAddress1": "28 FAITH ST",
                        "PatientAddress2": null,
                        "PatientSuburb": "PARRAMATTA",
                        "PatientPostcode": "2150",
                        "PatientState": "NSW",
                        "PatientSex": "F",
                        "PatientPhoneNumber": "0",
                        "PatientMobileNumber": "0",
                        "PatientEmail": null,
                        "PatientMedicareNumber": "5950073091",
                        "PatientMedicareSubNumerate": "1",
                        "PatientMedicareValidTo": "2016-12-31",
                        "Concession_PensionNumber": null,
                        "EntitlementNumber": null,
                        "DVANumber": null,
                        "DVACardColour": null,
                        "PatientBirthdate": "1984-03-16",
                        "PatientCTGFlag": "false",
                        "PatientIHI": "8003602345689155",
                        "Patient_Reserved_01": null,
                        "Patient_Reserved_02": null,
                        "Patient_Reserved_03": null,
                        "Patient_Reserved_04": null,
                        "Patient_Reserved_05": null
                    },
                    "Clinician": {
                        "DoctorPrescriberNumber": "469242",
                        "DoctorFirstName": "Howard",
                        "DoctorFamilyName": "Hertz",
                        "DoctorProviderNumber": "2145171X",
                        "DoctorMobileNumber": "0",
                        "DoctorEmail": "HowieHertz@superclinic.com.au",
                        "PracticeName": "Super Clinic",
                        "PracticeAddress1": "20 Trenerry Cres",
                        "PracticeAddress2": null,
                        "PracticeSuburb": "ABBOTSFORD",
                        "PracticePostcode": "3067",
                        "PracticeState": "VIC",
                        "PracticeEmail": "superclinic@superclinic.com.au",
                        "DoctorPhoneNumber": "1300700921",
                        "DoctorFaxNumber": "0",
                        "PrescribingSystemUsed": "Best Practice",
                        "PrescriberType": "M",
                        "PrescriberHPIO": "8003629900000429",
                        "PrescriberHPII": "8003614900014588",
                        "Clinician_Reserved_01": null,
                        "Clinician_Reserved_02": null,
                        "Clinician_Reserved_03": null,
                        "Clinician_Reserved_04": null,
                        "Clinician_Reserved_05": null
                    },
                    "PrescribedItem": {
                        "PrescriptionDate": "2022-03-30T00:00:00",
                        "ItemUniqueID": "17",
                        "ItemTradeName": "Karvea",
                        "ItemGenericName": "Irbesartan",
                        "ItemForm": "Tablet",
                        "ItemStrength": "150mg",
                        "ItemGenericIntention": "T",
                        "BrandSubstitutionNotAllowed": "false",
                        "PBSCode": "8247C",
                        "PBSManufacturerCode": "SW",
                        "Quantity": "30",
                        "UnusualQtyFlag": "false",
                        "ItemBarcode": "0",
                        "RouteAdministration": null,
                        "NumberOfRepeatsAuthorised": "5",
                        "PBS-DVAAuthorityNumber": "0",
                        "PhoneApprovalAuthorityNumber": null,
                        "ScheduleNumber": "4",
                        "PatientInstructions": "1 Daily",
                        "RepeatIntervals": "0",
                        "DoctorNotes": null,
                        "ReasonForPrescribing": null,
                        "Regulation24": "false",
                        "IsExtemp": "false",
                        "ExtemporaneousDescription": null,
                        "UnlistedItemRepatAuthority": "false",
                        "PrivatePrescription": "false",
                        "ScriptCTGAnnotation": null,
                        "AMT_MP": null,
                        "AMT_MPP": null,
                        "AMT_TPP": null,
                        "AMT_MPUU": null,
                        "AMT_TP": null,
                        "AMT_TPUU": null,
                        "AMT_CTPP": null,
                        "PrescribedItem_Reserved_01": null,
                        "PrescribedItem_Reserved_02": null,
                        "PrescribedItem_Reserved_03": null,
                        "PrescribedItem_Reserved_04": null,
                        "PrescribedItem_Reserved_05": null,
                        "TherapeuticGoodIdentificationCode": null,
                        "TherapeuticGoodIdentificationCodeSystem": null,
                        "TherapeuticGoodIdentificationCodeSystemName": null,
                        "TherapeuticGoodIdentificationCodeSystemVersion": null,
                        "TherapeuticGoodIdentificationDisplayName": null,
                        "AMT_CODE_SYSTEM": null,
                        "QuantityExtended": null,
                        "AMT_VERSION": null,
                        "PRIMARY_MEDICATION_CODE": null,
                        "RTACid": null,
                        "PrescriberScriptNumber": "3005",
                        "PrivacyStatement": "true",
                        "EmergencySupply": "false",
                        "ControlledSubstanceReference": null,
                        "SNOMED-CTReasonforPrescribe": "0",
                        "UnusualDoseFlag": "false"
                    }
                },
                "Tags": null,
                "UpdatedBy": null,
                "UpdatedDate": null,
                "DispensedDate": null,
                "CreatorVendorID": "175",
                "DispenserVendorID": null,
                "MedchartItemMetadata": null
            }
        },
        "SourceType": "Prescriber",
        "ConsolidatedSCIDs": null,
        "ViewConsent": null,
        "PatientRef": null,
        "MedchartMetadata": null,
        "Tags": {
            "Tag": {
                "Key": "PatientIHI",
                "Value": null
            }
        },
        "OperationResult": {
            "Status": "Success",
            "ErrorList": null
        }
    }
}