# Generated by Django 4.2.5 on 2023-11-02 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta_app', '0002_rename_userfollowersmodel_userfollowersfollowingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowersfollowingmodel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollowersfollowingmodel',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
