# Generated by Django 4.2.5 on 2023-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstoragewithsessionidmodel',
            name='reply',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chatstoragewithsessionidmodel',
            name='user_input',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
