# Generated by Django 4.2.9 on 2024-01-05 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('cre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commercialrealestate')),
            ],
            options={
                'db_table': 'cre_notes',
                'indexes': [models.Index(fields=['cre'], name='cre_notes_cre_id_ac68e4_idx')],
            },
        ),
    ]
