# Generated by Django 4.2.4 on 2024-03-03 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('media_file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upload-media/')),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'upload_media',
            },
        ),
    ]
