# Generated by Django 4.2.4 on 2023-09-12 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatstoragewithchatbotmodel_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstoragewithchatbotmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatstoragewithchatbotmodel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatting_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
