# Generated by Django 4.2.9 on 2024-01-05 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crenotesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCreLeads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_bookmarked', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('cre_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_lead', to='api.commercialrealestate')),
                ('cre_lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_lender', to='api.mortgagelender')),
                ('cre_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'save_cre_leads',
                'indexes': [models.Index(fields=['cre_lender'], name='save_cre_le_cre_len_36f8f9_idx')],
            },
        ),
    ]
