# Generated by Django 4.2.5 on 2023-09-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatstoragewithsessionidmodel_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatstoragewithsessionidmodel',
            name='reply',
        ),
    ]
