# Generated by Django 4.2.5 on 2023-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatstoragewithsessionidmodel_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgToPdfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
