# Generated by Django 4.2.13 on 2024-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatstoragewithsessionidmodel_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='DATASET/train/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
