# Generated by Django 4.2.13 on 2024-06-04 02:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skinimagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_to),
        ),
    ]
