# Generated by Django 4.2.4 on 2023-09-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatstoragewithsessionidmodel_sessionidstoremodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionidstoremodel',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
    ]
