# Generated by Django 4.2.5 on 2023-10-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scidmodel',
            name='scid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
