# Generated by Django 4.2.4 on 2023-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_permissionmodel_rolemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminAssignPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role_of_user',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'customer'), ('3', 'agent'), ('4', 'None')], default='4'),
        ),
    ]
