# Generated by Django 4.2.5 on 2023-10-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_scidmodel_scid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotmodel',
            old_name='api_key',
            new_name='production_api_key',
        ),
        migrations.AddField(
            model_name='chatbotmodel',
            name='test_api_key',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
