# Generated by Django 4.2.13 on 2024-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('otp', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
