# Generated by Django 4.2.5 on 2023-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_api_key_chatbotmodel_production_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_of_user',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'customer'), ('3', 'agent'), ('4', 'None'), ('5', 'client')], default='4', max_length=100),
        ),
    ]
