# Generated by Django 4.2.4 on 2023-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_superadminassignpermissionmodel_user_role_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatstoragewithsessionidmodel',
            name='reply',
        ),
    ]
