# Generated by Django 4.2.5 on 2023-10-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_role_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionidstoremodel',
            name='chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chatbotmodel'),
        ),
    ]
