# Generated by Django 4.2.4 on 2023-09-15 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_chatstoragewithsessionidmodel_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionidstoremodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
