# Generated by Django 4.2.13 on 2024-07-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sendotpmodel_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotpmodel',
            name='device_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
