# Generated by Django 4.2.5 on 2023-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatstoragewithsessionidmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionidstoremodel',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
