# Generated by Django 4.2.13 on 2024-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sendotpmodel_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendotpmodel',
            name='otp_vreified',
            field=models.BooleanField(default=False),
        ),
    ]
