# Generated by Django 4.2.5 on 2023-10-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sessionidstoremodel_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtopdfmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
