# Generated by Django 4.2.13 on 2024-07-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sendotpmodel_otp_vreified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendotpmodel',
            old_name='otp_vreified',
            new_name='otp_verified',
        ),
    ]
