# Generated by Django 4.2.5 on 2023-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_imgtopdfmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgtopdfmodel',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
