# Generated by Django 4.2.13 on 2024-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_otp_vreified_sendotpmodel_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=True),
        ),
    ]
