# Generated by Django 4.2.5 on 2024-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.JSONField(default=list)),
            ],
        ),
    ]
