# Generated by Django 4.2.5 on 2023-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_imgtopdfmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_subscription',
            field=models.IntegerField(blank=True, help_text='1.six months, 2.one year, 3.two years', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trail_period',
            field=models.IntegerField(blank=True, help_text='1.six months, 2.one year, 3.two years', null=True),
        ),
    ]
