# Generated by Django 4.2.5 on 2023-11-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_table_id_59f7cf_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
