# Generated by Django 4.2.5 on 2023-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_user_options_remove_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_id_59f7cf_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_table_first_n_20ec49_idx'),
        ),
    ]
