# Generated by Django 4.2.5 on 2023-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_table_first_n_20ec49_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
