# Generated by Django 4.2.5 on 2023-11-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_user_user_table_id_59f7cf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_first_n_20ec49_idx',
        ),
    ]
