# Generated by Django 4.2.5 on 2023-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_user_table_first_n_20ec49_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_first_n_20ec49_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_of_user'], name='user_table_role_of_39f9ed_idx'),
        ),
    ]
