# Generated by Django 4.2.5 on 2023-11-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_user_table_role_of_39f9ed_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_role_of_39f9ed_idx',
        ),
    ]
