# Generated by Django 4.2.5 on 2023-11-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_user_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_role_of_39f9ed_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_table_first_n_20ec49_idx'),
        ),
    ]
