# Generated by Django 4.2.5 on 2023-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_user_user_table_first_n_20ec49_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_table_first_n_20ec49_idx'),
        ),
    ]
