# Generated by Django 4.2.5 on 2023-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_user_user_table_first_n_20ec49_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_first_n_20ec49_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_table_email_f90d31_idx'),
        ),
    ]
