# Generated by Django 4.2.5 on 2023-11-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_user_user_table_first_n_20ec49_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_email_f90d31_idx',
        ),
    ]
