# Generated by Django 4.2.5 on 2023-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_user_user_table_email_f90d31_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_table_email_f90d31_idx'),
        ),
    ]
