# Generated by Django 4.2.5 on 2023-11-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_user_table_email_f90d31_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_email_f90d31_idx',
        ),
    ]
