# Generated by Django 4.2.5 on 2023-11-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_user_user_table_email_f90d31_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionidstoremodel',
            index=models.Index(fields=['session_id'], name='session_mod_session_c3af51_idx'),
        ),
        migrations.AlterModelTable(
            name='sessionidstoremodel',
            table='session_model',
        ),
    ]
