# Generated by Django 4.2.5 on 2023-11-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sessionidstoremodel_session_mod_session_c3af51_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessionidstoremodel',
            name='session_mod_session_c3af51_idx',
        ),
        migrations.AlterModelTable(
            name='sessionidstoremodel',
            table=None,
        ),
    ]
