# Generated by Django 4.2.5 on 2023-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_sessionidstoremodel_session_mod_session_c3af51_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_table_first_n_20ec49_idx'),
        ),
    ]
