# Generated by Django 4.2.5 on 2023-11-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_user_user_table_first_n_20ec49_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_table_first_n_20ec49_idx',
        ),
    ]
