# Generated by Django 4.2.5 on 2023-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_user_user_table_first_n_20ec49_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCsvFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files')),
            ],
        ),
    ]
