# Generated by Django 4.2.4 on 2023-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_savecsvfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scidmodel',
            name='scid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
