# Generated by Django 4.2.4 on 2023-11-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_scidmodel_scid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScidModel',
        ),
    ]
