# Generated by Django 4.2.4 on 2023-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_delete_scidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecsvfilemodel',
            name='csv_file',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
