# Generated by Django 4.2.5 on 2023-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_delete_scidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField(blank=True, choices=[(1, 'first'), (2, 'second')], null=True)),
            ],
        ),
    ]
