# Generated by Django 4.2.4 on 2023-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_savecsvfilemodel_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecsvfilemodel',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files'),
        ),
    ]
