# Generated by Django 4.2.5 on 2023-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_randommodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='randommodel',
            table='random_table',
        ),
    ]
