# Generated by Django 4.2.5 on 2023-11-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_randommodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
