# Generated by Django 4.2.5 on 2023-11-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_delete_randommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'random_model',
            },
        ),
    ]
