# Generated by Django 4.2.5 on 2023-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_randommodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='randommodel',
            index=models.Index(fields=['name'], name='random_mode_name_544f66_idx'),
        ),
    ]
