# Generated by Django 4.2.5 on 2023-11-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_randommodel_random_mode_name_544f66_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='randommodel',
            name='random_mode_name_544f66_idx',
        ),
    ]
