# Generated by Django 4.2.5 on 2023-12-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_randommodel_random_mode_name_544f66_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='randommodel',
            index=models.Index(fields=['id'], name='random_mode_id_a866b8_idx'),
        ),
    ]
