# Generated by Django 4.2.4 on 2023-12-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_savecsvfilemodel_csv_file'),
        ('api', '0058_borrowers_collateralmodel_mortgagelender_and_more'),
    ]

    operations = [
    ]
