# Generated by Django 4.2.4 on 2023-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_merge_20231229_1952'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='borrowers',
            index=models.Index(fields=['id'], name='borrowers_m_id_0d8c05_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralmodel',
            index=models.Index(fields=['id'], name='collateral__id_6eadd7_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialrealestate',
            index=models.Index(fields=['id'], name='commercial__id_b50569_idx'),
        ),
        migrations.AddIndex(
            model_name='mortgagelender',
            index=models.Index(fields=['id'], name='lenders_mod_id_d85a10_idx'),
        ),
        migrations.AddIndex(
            model_name='staterealestate',
            index=models.Index(fields=['id'], name='state_model_id_ee8d44_idx'),
        ),
        migrations.AlterModelTable(
            name='borrowers',
            table='borrowers_model',
        ),
        migrations.AlterModelTable(
            name='collateralmodel',
            table='collateral_model',
        ),
        migrations.AlterModelTable(
            name='commercialrealestate',
            table='commercial_realestate_model',
        ),
        migrations.AlterModelTable(
            name='mortgagelender',
            table='lenders_model',
        ),
        migrations.AlterModelTable(
            name='staterealestate',
            table='state_model',
        ),
    ]
