# Generated by Django 4.2.4 on 2023-12-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_borrowers_borrowers_m_id_0d8c05_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialrealestate',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
