# Generated by Django 4.2.4 on 2023-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_commercialrealestate_loan_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='borrowers',
            name='borrowers_m_id_0d8c05_idx',
        ),
        migrations.AddIndex(
            model_name='borrowers',
            index=models.Index(fields=['borrower'], name='borrowers_m_borrowe_1b70cd_idx'),
        ),
    ]
