# Generated by Django 4.2.4 on 2023-12-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_borrowers_borrowers_m_id_0d8c05_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collateralmodel',
            name='collateral__id_6eadd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='mortgagelender',
            name='lenders_mod_id_d85a10_idx',
        ),
        migrations.RemoveIndex(
            model_name='staterealestate',
            name='state_model_id_ee8d44_idx',
        ),
        migrations.AddIndex(
            model_name='collateralmodel',
            index=models.Index(fields=['collateral_type'], name='collateral__collate_a26e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='mortgagelender',
            index=models.Index(fields=['lender'], name='lenders_mod_lender_3cc47e_idx'),
        ),
        migrations.AddIndex(
            model_name='staterealestate',
            index=models.Index(fields=['state'], name='state_model_state_1570ac_idx'),
        ),
    ]
