# Generated by Django 4.2.4 on 2024-01-01 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_collateralmodel_collateral__id_6eadd7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneCommercialRealEstate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('borrower', models.CharField(blank=True, max_length=200, null=True)),
                ('lender', models.CharField(blank=True, max_length=200, null=True)),
                ('origination_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('collateral_type', models.CharField(blank=True, max_length=200, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField()),
                ('notes_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('is_booked', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'clone_commercial_realestate_model',
                'indexes': [models.Index(fields=['borrower', 'lender'], name='clone_comme_borrowe_d35006_idx')],
            },
        ),
    ]
