# Generated by Django 4.2.4 on 2024-03-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElasticSearch',
            new_name='ElasticSearchModel',
        ),
    ]
