# Generated by Django 4.2.4 on 2024-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_backend', '0002_rename_elasticsearch_elasticsearchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticsearchmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='elasticsearchmodel',
            name='title',
            field=models.TextField(),
        ),
    ]
