data = {
    "message": "",
    "messageType": "ERX001",
    "conversationId": "123e4567-e89b-12d3-a456-426614174000",
    "entityId": "HTWKV",
    "destinationId": "00000",
    "scid": "2HTWKV99T1X2XGY892",
    "Items": [
        {
            "Sequence": 1,
            "State": "Active",
            "Content": {
                "Patient": {
                    "PatientUniqueID": consultation.user.id,
                    "PatientNumber": consultation.user.id,
                    "PatientFamilyName": consultation.user.last_name,
                    "PatientFirstName": consultation.user.first_name,
                    "PatientMedicareFamilyName": None,
                    "PatientMedicareFirstName": None,
                    "PatientTitle": "MISS" if consultation.user.gender == "2" else "MR",
                    "PatientAddress1": consultation.user.address,
                    "PatientAddress2": None,
                    "PatientSuburb": consultation.user.suburb,
                    "PatientPostcode": consultation.user.zipcode,
                    "PatientState": consultation.user.state,
                    "PatientSex": "F" if consultation.user.gender == "2" else "M",
                    "PatientPhoneNumber": consultation.user.phone_no,
                    "PatientMobileNumber": consultation.user.emergency_contact_number,
                    "PatientEmail": consultation.user.email,
                    "PatientMedicareNumber": "5950073091",
                    "PatientMedicareSubNumerate": 1,
                    "PatientMedicareValidTo": "2016-12-31",
                    "Concession_PensionNumber": consultation.user.concession_card,
                    "EntitlementNumber": None,
                    "DVANumber": consultation.user.card_number,
                    "DVACardColour": consultation.user.card_color,
                    "PatientBirthdate": consultation.user.dob,
                    "PatientCTGFlag": False,
                    "PatientIHI": consultation.user.medical_registartion,
                    "Patient_Reserved_01": None,
                    "Patient_Reserved_02": None,
                    "Patient_Reserved_03": None,
                    "Patient_Reserved_04": None,
                    "Patient_Reserved_05": None
                },
                "Clinician": {
                    "DoctorPrescriberNumber": consultation.escript_assigned_doctor.doctor_prescriber_number,
                    "DoctorFirstName": consultation.escript_assigned_doctor.first_name,
                    "DoctorFamilyName": consultation.escript_assigned_doctor.last_name,
                    "DoctorProviderNumber": consultation.escript_assigned_doctor.doctor_provider_number,
                    "DoctorMobileNumber": consultation.escript_assigned_doctor.phone_no,
                    "DoctorEmail": consultation.escript_assigned_doctor.email,
                    "PracticeName": consultation.escript_assigned_doctor.first_name,
                    "PracticeAddress1": consultation.escript_assigned_doctor.address,
                    "PracticeAddress2": None,
                    "PracticeSuburb": consultation.escript_assigned_doctor.suburb,
                    "PracticePostcode": consultation.escript_assigned_doctor.zipcode,
                    "PracticeState": consultation.escript_assigned_doctor.state,
                    "PracticeEmail": consultation.escript_assigned_doctor.email,
                    "DoctorPhoneNumber": consultation.escript_assigned_doctor.emergency_contact_number,
                    "DoctorFaxNumber": "0",
                    "PrescribingSystemUsed": "Best Practice",
                    "PrescriberType": "M",
                    "PrescriberHPIO": "8003622500084471",
                    "PrescriberHPII": "8003614900014588",
                    "Clinician_Reserved_01": None,
                    "Clinician_Reserved_02": None,
                    "Clinician_Reserved_03": None,
                    "Clinician_Reserved_04": None,
                    "Clinician_Reserved_05": None
                },
                "PrescribedItem": {
                    "PrescriptionDate": "2022-03-30T00:00:00",
                    "ItemUniqueID": "17",
                    "ItemTradeName": "Karvea",
                    "ItemGenericName": "Irbesartan",
                    "ItemForm": "Tablet",
                    "ItemStrength": "150mg",
                    "ItemGenericIntention": "T",
                    "BrandSubstitutionNotAllowed": False,
                    "PBSCode": "8247C",
                    "PBSManufacturerCode": "SW",
                    "Quantity": "30",
                    "UnusualQtyFlag": False,
                    "ItemBarcode": "0",
                    "RouteAdministration": None,
                    "NumberOfRepeatsAuthorised": "5",
                    "PBS-DVAAuthorityNumber": "0",
                    "PhoneApprovalAuthorityNumber": None,
                    "ScheduleNumber": "4",
                    "PatientInstructions": "1 Daily",
                    "RepeatIntervals": "0",
                    "DoctorNotes": None,
                    "ReasonForPrescribing": None,
                    "Regulation24": False,
                    "IsExtemp": False,
                    "ExtemporaneousDescription": None,
                    "UnlistedItemRepatAuthority": False,
                    "PrivatePrescription": False,
                    "ScriptCTGAnnotation": None,
                    "AMT_MP": None,
                    "AMT_MPP": None,
                    "AMT_TPP": None,
                    "AMT_MPUU": None,
                    "AMT_TP": None,
                    "AMT_TPUU": None,
                    "AMT_CTPP": None,
                    "PrescribedItem_Reserved_01": None,
                    "PrescribedItem_Reserved_02": None,
                    "PrescribedItem_Reserved_03": None,
                    "PrescribedItem_Reserved_04": None,
                    "PrescribedItem_Reserved_05": None,
                    "TherapeuticGoodIdentificationCode": None,
                    "TherapeuticGoodIdentificationCodeSystem": None,
                    "TherapeuticGoodIdentificationCodeSystemName": None,
                    "TherapeuticGoodIdentificationCodeSystemVersion": None,
                    "TherapeuticGoodIdentificationDisplayName": None,
                    "AMT_CODE_SYSTEM": None,
                    "QuantityExtended": None,
                    "AMT_VERSION": None,
                    "PRIMARY_MEDICATION_CODE": None,
                    "RTACid": None,
                    "PrescriberScriptNumber": "3005",
                    "PrivacyStatement": True,
                    "EmergencySupply": False,
                    "ControlledSubstanceReference": None,
                    "SNOMED-CTReasonforPrescribe": "0",
                    "UnusualDoseFlag": False
                }
            }
        }
    ]
}